/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BinRouteImport } from './routes/bin'
import { Route as CashbookRouteImport } from './routes/cashbook'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as KhataRouteImport } from './routes/khata'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as WasoolaRouteImport } from './routes/wasoola'
import { Route as KhataCustomerIdRouteImport } from './routes/khata.$customerId'
import { Route as SaleSaleIdRouteImport } from './routes/sale.$saleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BinRoute = BinRouteImport.update({
  id: '/bin',
  path: '/bin',
  getParentRoute: () => rootRouteImport,
} as any)
const CashbookRoute = CashbookRouteImport.update({
  id: '/cashbook',
  path: '/cashbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataRoute = KhataRouteImport.update({
  id: '/khata',
  path: '/khata',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const WasoolaRoute = WasoolaRouteImport.update({
  id: '/wasoola',
  path: '/wasoola',
  getParentRoute: () => rootRouteImport,
} as any)
const KhataCustomerIdRoute = KhataCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => KhataRoute,
} as any)
const SaleSaleIdRoute = SaleSaleIdRouteImport.update({
  id: '/sale/$saleId',
  path: '/sale/$saleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bin': typeof BinRoute
  '/cashbook': typeof CashbookRoute
  '/items': typeof ItemsRoute
  '/khata': typeof KhataRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/wasoola': typeof WasoolaRoute
  '/khata/$customerId': typeof KhataCustomerIdRoute
  '/sale/$saleId': typeof SaleSaleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bin': typeof BinRoute
  '/cashbook': typeof CashbookRoute
  '/items': typeof ItemsRoute
  '/khata': typeof KhataRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/wasoola': typeof WasoolaRoute
  '/khata/$customerId': typeof KhataCustomerIdRoute
  '/sale/$saleId': typeof SaleSaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bin': typeof BinRoute
  '/cashbook': typeof CashbookRoute
  '/items': typeof ItemsRoute
  '/khata': typeof KhataRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/wasoola': typeof WasoolaRoute
  '/khata/$customerId': typeof KhataCustomerIdRoute
  '/sale/$saleId': typeof SaleSaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bin'
    | '/cashbook'
    | '/items'
    | '/khata'
    | '/privacy'
    | '/wasoola'
    | '/khata/$customerId'
    | '/sale/$saleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bin'
    | '/cashbook'
    | '/items'
    | '/khata'
    | '/privacy'
    | '/wasoola'
    | '/khata/$customerId'
    | '/sale/$saleId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bin'
    | '/cashbook'
    | '/items'
    | '/khata'
    | '/privacy'
    | '/wasoola'
    | '/khata/$customerId'
    | '/sale/$saleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BinRoute: typeof BinRoute
  CashbookRoute: typeof CashbookRoute
  ItemsRoute: typeof ItemsRoute
  KhataRoute: typeof KhataRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  WasoolaRoute: typeof WasoolaRoute
  SaleSaleIdRoute: typeof SaleSaleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bin': {
      id: '/bin'
      path: '/bin'
      fullPath: '/bin'
      preLoaderRoute: typeof BinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbook': {
      id: '/cashbook'
      path: '/cashbook'
      fullPath: '/cashbook'
      preLoaderRoute: typeof CashbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata': {
      id: '/khata'
      path: '/khata'
      fullPath: '/khata'
      preLoaderRoute: typeof KhataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wasoola': {
      id: '/wasoola'
      path: '/wasoola'
      fullPath: '/wasoola'
      preLoaderRoute: typeof WasoolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khata/$customerId': {
      id: '/khata/$customerId'
      path: '/$customerId'
      fullPath: '/khata/$customerId'
      preLoaderRoute: typeof KhataCustomerIdRouteImport
      parentRoute: typeof KhataRoute
    }
    '/sale/$saleId': {
      id: '/sale/$saleId'
      path: '/sale/$saleId'
      fullPath: '/sale/$saleId'
      preLoaderRoute: typeof SaleSaleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KhataRouteChildren {
  KhataCustomerIdRoute: typeof KhataCustomerIdRoute
}

const KhataRouteChildren: KhataRouteChildren = {
  KhataCustomerIdRoute: KhataCustomerIdRoute,
}

const KhataRouteWithChildren = KhataRoute._addFileChildren(KhataRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BinRoute: BinRoute,
  CashbookRoute: CashbookRoute,
  ItemsRoute: ItemsRoute,
  KhataRoute: KhataRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  WasoolaRoute: WasoolaRoute,
  SaleSaleIdRoute: SaleSaleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
